name: Development build

on:
  pull_request:
    branches-ignore:
      - 'l10n_main'
    types: [opened, reopened]
  push:
    branches-ignore:
      - 'l10n_main'
  workflow_dispatch:

jobs:
  build:
    name: Development build
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - platform: 2
            platform_name: ios

    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Checkout repository submodules
        run: git submodule update --init --recursive

      - name: Install build tools
        run: brew install ldid make

      - name: Get gl4es latest commit hash
        id: gl4es-sha
        shell: bash
        run: |
          echo "sha=$(git ls-remote https://github.com/PojavLauncherTeam/gl4es-114-extra refs/heads/master | grep -io '^\S*')" >> $GITHUB_OUTPUT

      - name: Cache gl4es
        uses: actions/cache@main
        if: false # use gl4es 1.1.5
        id: gl4es-cache
        with:
          path: gl4es/libs
          key: gl4es-holy-ios-shared-2-${{ steps.gl4es-sha.outputs.sha }}

      - name: Get gl4es
        if: false && steps.gl4es-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@main
        with:
          repository: 'PojavLauncherTeam/gl4es-114-extra'
          path: 'gl4es'

      - name: Build gl4es
        if: false && steps.gl4es-cache.outputs.cache-hit != 'true'
        continue-on-error: true
        run: |
          cd gl4es
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "github-actions"
          wget https://github.com/leetal/ios-cmake/raw/master/ios.toolchain.cmake
          cmake -B build -DCMAKE_TOOLCHAIN_FILE=ios.toolchain.cmake -DDEFAULT_ES=2 \
            -DNOX11=ON -DNOEGL=OFF -DSTATICLIB=OFF -DPLATFORM=OS64 \
            -DCMAKE_C_FLAGS=-Wno-error=implicit-function-declaration
          cmake --build build --config RelWithDebInfo --target GL
          cp -R lib/libGL.dylib ../Natives/resources/Frameworks/libgl4es_114.dylib

      - name: Build for ${{ matrix.platform_name }}
        run: |
          export PATH=/opt/homebrew/bin:$PATH
          export SLIMMED=1
          if [ "${{ matrix.platform_name }}" == "ios" ]; then
            gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }}
            gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }} TROLLSTORE_JIT_ENT=1
          fi

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_OUTPUT

      - name: Create Draft Release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: dev-${{ steps.date.outputs.date }}
          name: Development Build - ${{ steps.date.outputs.date }}
          draft: true
          prerelease: true
          generate_release_notes: true
          files: |
            artifacts/*.ipa
            artifacts/*.tipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload IPA (PR only)
        uses: actions/upload-artifact@main
        if: github.event_name == 'pull_request'
        with:
          name: amethyst-${{ matrix.platform_name }}.ipa
          path: artifacts/*-${{ matrix.platform_name }}.ipa

      - name: Upload TIPA (PR only)
        uses: actions/upload-artifact@main
        if: github.event_name == 'pull_request'
        with:
          name: amethyst-${{ matrix.platform_name }}-trollstore.tipa
          path: artifacts/*-${{ matrix.platform_name }}-trollstore.tipa
